apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-proget-poc-msi
  namespace: ${NAMESPACE}
spec:
  provider: azure
  parameters:
    cloudName: ""
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    tenantId: $AKS_IDENTITY_TENANT_ID
    keyvaultName: $KEY_VAULT_NAME
    userAssignedIdentityID: $AKS_KEY_VAULT_IDENTITY_CLIENT_ID
    objects: |
      array:
        - |
          objectName: sql-connection-string
          objectType: secret
          objectVersion: ""
  secretObjects:
  - data:
    - key: PROGET_SQL_CONNECTION_STRING
      objectName: sql-connection-string
    type: Opaque
